StocksApplication.Web/Controllers/StocksController.cs
using Microsoft.AspNetCore.Mvc;
using StocksApplication.Core.Contracts.ServiceContracts;
using StocksApplication.Core.Models;
using StocksApplication.Web.ViewModels;

namespace StocksApplication.Web.Controllers
{
	public class StocksController : Controller
    {
        #region private readonly fields
        private readonly IFinnhubService _finnhubService;
        private readonly IConfiguration _configuration;
        private readonly ILogger<StocksController> _logger;
        #endregion

        #region constructor
        public StocksController(IFinnhubService finnhubService, ILogger<StocksController> logger, IConfiguration configuration)
        {
            _finnhubService = finnhubService;
            _logger = logger;
            _configuration = configuration;
        }
        #endregion

        [HttpGet]
        [Route("/Stocks/Explore")]
        public async Task<IActionResult> Explore(string? stock)
        {
            ViewBag.StockSymbol = stock ?? null;
            _logger.LogInformation($"Executing StocksController.Explore({stock ?? string.Empty})");

            try
            {
                List<Dictionary<string, string>> stocksResponse = await _finnhubService.GetStocks()
                    ?? throw new Exception("Failed to retrieve stocks data from FinnhubAPI.");

                string[] topStockSymbols = _configuration["Top25PopularStocks"].Split(',')
                    ?? throw new Exception("Top 25 Popular Stocks not available in the current configuration.");

                var stocks = new List<Stock>();

                foreach (var stockSymbol in topStockSymbols)
                {
                    Dictionary<string, string>? includedStock = stocksResponse
                        .FirstOrDefault(r => r.ContainsKey("symbol") && r["symbol"] == stockSymbol)
                        ?? throw new Exception($"Stock with symbol {stockSymbol} could not be found in the FinnhubAPI Response.");

                    stocks.Add(new Stock
                    {
                        StockName = includedStock["description"] ?? "NAME NOT FOUND",
                        StockSymbol = includedStock["symbol"] ?? "ERR"
                    });
                }

                return View(new StocksExploreViewModel { Stocks = stocks });
            }

            catch (Exception ex)
            {
                _logger.LogWarning(ex.GetType().Name, ex.Message);
                return View(null);
            }
        }
    }
}

StocksApplication.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
	<head>
		<title>STOCKS - @ViewBag.Title</title>
		<link rel="stylesheet" href="~/StyleSheet.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" />
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	</head>
	<body>
		<div class="container">
			<div class="header"><span class="app-title">STOCKS </span><i class="fa-solid fa-money-bill-trend-up logo"></i>
				<ul>
					<li>
						<a asp-controller="Stocks" asp-action="Explore">Explore Stocks</a>
					</li>
					|
					<li>
						<a asp-controller="Trade" asp-action="Index">Trade</a>
					</li>
					|
					<li>
						<a asp-controller="Trade" asp-action="Orders">Orders</a>
					</li>
				</ul>
			</div>

			<div class="page-content">
				@RenderBody()
			</div>
		</div>
		@RenderSection("Scripts", false)
	</body>
</html>